"""describe changes

Revision ID: 9b6bcc9a8b2e
Revises: 
Create Date: 2025-02-16 03:40:56.661360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6bcc9a8b2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_table_id'), 'example_table', ['id'], unique=False)
    op.create_index(op.f('ix_example_table_name'), 'example_table', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_table_name'), table_name='example_table')
    op.drop_index(op.f('ix_example_table_id'), table_name='example_table')
    op.drop_table('example_table')
    # ### end Alembic commands ###
